apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netshoot-pid-net-ipc-access-daemonset-pod
  labels:
    name: netshoot-pid-net-ipc-access-daemonset-pod
spec:
  selector:
    matchLabels:
      name: netshoot-pid-net-ipc-access-daemonset-pod
  template:
    metadata:
      labels:
        name: netshoot-pid-net-ipc-access-daemonset-pod
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
      - name: netshoot-with-docker
        image: angadisachin2/netshoot
        command: [ "bash", "-c", "sleep 5h" ]
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/run/
          name: docker-sock
          # readOnly: true
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/
          type: Directory
